configure: better check for executables

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -106,37 +106,43 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-if [[ ! -n $QMAKE && ! -f $QMAKE ]]; then
-    QMAKE=`which qmake 2> /dev/null`
-    if [[ ! -n $QMAKE || ! -f $QMAKE ]]; then
-        QMAKE=$QTDIR/bin/qmake
-    fi
-fi
-if [ ! -f $QMAKE ]; then
-    echo "$BASENAME: Unable to find 'qmake'. Try \`QTDIR=/path/to/qt $0' or \`QMAKE=/path/to/qmake $0'."
-    exit 1
-fi
-
-if [[ ! -n $LRELEASE && ! -f $LRELEASE ]]; then
-    LRELEASE=`which lrelease 2> /dev/null`
-    if [[ ! -n $LRELEASE || ! -f $LRELEASE ]]; then
-        LRELEASE=$QTDIR/bin/lrelease
-    fi
-fi
-if [ ! -f "$LRELEASE" ]; then
-    echo "$BASENAME: Unable to find 'lrelease'. Try \`QTDIR=/path/to/qt $0' or \`LRELEASE=/path/to/lrelease $0'."
-    exit 1
-fi
-
 QMAKE_CACHE=`pwd`/.qmake.cache
 [ -f $QMAKE_CACHE ] && rm -f $QMAKE_CACHE
+
+check_executable()
+{
+    VNAME="$1"
+    FNAME="$2"
+
+    echo -n "checking for $FNAME..."
+
+    if [[ -z "${!VNAME}" ]]; then
+        eval ${VNAME}=$(which "$FNAME" 2>/dev/null)
+        if [[ -z "${!VNAME}" ]]; then
+            echo "no"
+            echo "$BASENAME: Unable to find '$FNAME'. Check the PATH environment variable or try \`$VNAME=/path/to/$FNAME $0'"
+            exit 1
+        fi
+    fi
+    if [[ ! -f "${!VNAME}" ]]; then
+        echo "no"
+        echo "$BASENAME: '${!VNAME}': No such file or directory."
+        exit 1
+    fi
+
+    echo "${!VNAME}"
+}
+
+check_executable QMAKE qmake
+check_executable LRELEASE lrelease
+echo "LRELEASE = $LRELEASE" >> $QMAKE_CACHE
+check_executable PKG_CONFIG pkg-config
+echo "PKG_CONFIG = $PKG_CONFIG" >> $QMAKE_CACHE
 
 [ -n "$CFLAGS" ]   && echo "QMAKE_CFLAGS += ${CFLAGS}"     >> $QMAKE_CACHE
 [ -n "$CXXFLAGS" ] && echo "QMAKE_CXXFLAGS += ${CXXFLAGS}" >> $QMAKE_CACHE
 [ -n "$LDFLAGS" ]  && echo "QMAKE_LFLAGS += ${LDFLAGS}"    >> $QMAKE_CACHE
 
-[ -z "$PKG_CONFIG" ] && PKG_CONFIG=pkg-config
-echo "PKG_CONFIG = $PKG_CONFIG" >> $QMAKE_CACHE
 
 pkg_check_lib()
 {
@@ -148,19 +154,11 @@ pkg_check_lib()
         exit 1
     fi
 }
-
-if [ `which $PKG_CONFIG 2> /dev/null` ]; then
-    echo "checking for pkg-config... yes"
-    [ $BUILD_GSTREAMER == "yes" ]           && pkg_check_lib gstreamer-1.0
-    [ $BUILD_GSTREAMER_TAGREADER == "yes" ] && pkg_check_lib gstreamer-pbutils-1.0
-    [ $BUILD_VLC == "yes" ]                 && pkg_check_lib libvlc
-    [ $BUILD_TAGLIB == "yes" ]              && pkg_check_lib taglib
-    [ $BUILD_PHONON == "yes" ]              && pkg_check_lib phonon
-else
-    echo "$BASENAME: Unable to find 'pkg-config'. Check PATH environment variable."
-    echo
-    exit 1
-fi
+[ $BUILD_GSTREAMER == "yes" ]           && pkg_check_lib gstreamer-1.0
+[ $BUILD_GSTREAMER_TAGREADER == "yes" ] && pkg_check_lib gstreamer-pbutils-1.0
+[ $BUILD_VLC == "yes" ]                 && pkg_check_lib libvlc
+[ $BUILD_TAGLIB == "yes" ]              && pkg_check_lib taglib
+[ $BUILD_PHONON == "yes" ]              && pkg_check_lib phonon
 
 [ $BUILD_GSTREAMER == "yes" ]           && QMAKE_CONFIG="$QMAKE_CONFIG gstreamer"
 [ $BUILD_GSTREAMER_TAGREADER == "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG gstreamer-tagreader"
@@ -194,8 +192,6 @@ echo "N_CONFIG_SUCCESS = yes" >> $QMAKE_CACHE
 [ -z "$NULLOY_BUILD_TMP_DIR" ] && NULLOY_BUILD_TMP_DIR=`pwd`/.tmp
 [ ! -d "$NULLOY_BUILD_TMP_DIR" ] && mkdir $NULLOY_BUILD_TMP_DIR
 echo "TMP_DIR = $NULLOY_BUILD_TMP_DIR" >> $QMAKE_CACHE
-
-echo "LRELEASE = $LRELEASE" >> $QMAKE_CACHE
 
 if [ `uname | grep -i darwin` ]; then
     QMAKE_EXTRA_OPTIONS="-spec macx-g++"
